version: '3'

services:
    database:
        container_name: database
        image: 'postgres:14.7'
        environment:
            POSTGRES_PASSWORD: "docker"
            POSTGRES_USER: "docker"
            POSTGRES_DB: "cofrinho"
        volumes:
            - ./.database:/var/lib/postgresql/data
        ports:
            - 5433:5432
    backend:
        container_name: backend
        build: backend
        depends_on:
            - database
        env_file:
            - ./backend/.env
        ports:
            - 8080:8080